server.port=8080
spring.datasource.url=jdbc:mysql://10.25.137.197/expense-tracker
spring.datasource.username=root
spring.datasource.password=vcxroot2024!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework=INFO
logging.level.com.example.expensetracker=DEBUG